### ISSUE TITLE
Uncaught TypeError: FormNapper requires an HTMLFormElement element or the id string of one.

### ISSUE THREAD

**Issue by ghost** [braintree/form-napper#6]
I can't figure out what the problem is here. I'm defenitely passing the `id` of a `form` element to `braintree.setup()` but I keep getting

```
Uncaught TypeError: FormNapper requires an HTMLFormElement element or the id string of one.
```

I've looked everywhere but I can't find a solution to this. As far as I can tell I'm following the documentation.

This is how I'm calling the setup function:

``` java
private final static String CREDIT_CARD_FORM_ID = "credit-card-form";

@Override
public void setServerToken(String serverToken) {
    LOGGER.fine("Setting server token ..");

    LOGGER.fine(".. for credit card form");
    this.setupCreditCardForm(CREDIT_CARD_FORM_ID, serverToken);
}

private native void setupCreditCardForm(String domId, String serverToken) /*-{      
    braintree.setup(
        serverToken,
        "custom",
        {
            id: domId,
            hostedFields: {
                number: {
                    selector: "#card-number"
                },
                cvv: {
                    selector: "#cvv"
                },
                expirationDate: {
                    selector: "#expiration-date"
                }
            }
        });
}-*/;
```

Whereas this is the form I'm using (note this is UiBinder xml)

``` xml
<g:HTML>

    <form id="credit-card-form" action="/app/create-credit-card" method="post" target="hidden-iframe">

        <label for="card-number">Card Number</label>
        <div id="card-number"/>

        <label for="cvv">CVV</label>
        <div id="cvv"/>

        <label for="expiration-date">Expiration Date</label>
        <div id="expiration-date"/>

        <input type="submit" value="Add Credit Card" />                     

    </form>
</g:HTML>
```

See on [stackoverflow](http://stackoverflow.com/questions/38807955/uncaught-typeerror-formnapper-requires-an-htmlformelement-element-or-the-id-str)

**Comment by crookedneighbor** [comment]
It looks to me like [your question was answered on StackOverflow](http://stackoverflow.com/a/38813017/2601552) and it wasn't actually an issue with form-napper. If I'm mistaken, feel free to re-open this!

**Comment by ghost** [comment]
Yes, the issue was cause by myself as I injected the JavaScript code wrong into my GWT application. Should anybody read this having the same issue: Check out the stackoverflow question above!

Sorry for disturbance!
